// Mocks generated by Mockito 5.4.6 from annotations
// in financy_control/test/services/auth/auth_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:financy_control/core/data/data.dart' as _i4;
import 'package:financy_control/core/models/user_model.dart' as _i5;
import 'package:financy_control/services/auth/auth_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i2.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.DataResult<_i5.UserModel>> signUp(
    _i5.UserInputModel? userInput,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signUp, [userInput]),
            returnValue: _i3.Future<_i4.DataResult<_i5.UserModel>>.value(
              _i6.dummyValue<_i4.DataResult<_i5.UserModel>>(
                this,
                Invocation.method(#signUp, [userInput]),
              ),
            ),
          )
          as _i3.Future<_i4.DataResult<_i5.UserModel>>);

  @override
  _i3.Future<_i4.DataResult<_i5.UserModel>> signIn({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signIn, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i3.Future<_i4.DataResult<_i5.UserModel>>.value(
              _i6.dummyValue<_i4.DataResult<_i5.UserModel>>(
                this,
                Invocation.method(#signIn, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.DataResult<_i5.UserModel>>);

  @override
  _i3.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i4.DataResult<bool>> forgotPassword(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#forgotPassword, [email]),
            returnValue: _i3.Future<_i4.DataResult<bool>>.value(
              _i6.dummyValue<_i4.DataResult<bool>>(
                this,
                Invocation.method(#forgotPassword, [email]),
              ),
            ),
          )
          as _i3.Future<_i4.DataResult<bool>>);
}
